# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Development
    url: development/
    weight: 30
#  - name: Dev
#    url: dev/
#    weight: 40
#  - name: Community
#    url: community/
#    weight: 50

sidebar:
  - identifier: more
    name: Having issues?
#    params:
#      type: separator
    weight: 3
    url: "https://github.com/AusARG/pipesnake/issues"
#  - identifier: community
#    name: "Community"
#    pageRef: "/community"
#    weight: 2
#  - identifier: hugoDocs
#    name: "Hugo Docs ↗"
#    url: "https://docs.hugoblox.com"
#    weight: 3
